name = "envhub-backend"
main = "src/index.ts"
compatibility_date = "2024-12-28"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "EnvHub"
# database_id = "4e1e8373-cd21-4697-bacf-83afbadfbe0b"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1